name: Migrations in Production
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
jobs:
  Migration:
    environment: production
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: npm install
      - name: Run Migrations
        run: npx prisma migrate deploy